name: Update Download Counter

on:
  release:
    types: [published]

jobs:
  update-counter:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update download count
        run: |
          COUNTER_FILE="download_count.txt"
          
          # Check if counter file exists
          if [ ! -f $COUNTER_FILE ]; then
            echo "0" > $COUNTER_FILE
          fi
          
          # Increment counter
          COUNT=$(cat $COUNTER_FILE)
          NEW_COUNT=$((COUNT + 1))
          
          echo $NEW_COUNT > $COUNTER_FILE
          
          # Commit the updated counter file
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add $COUNTER_FILE
          git commit -m "Increment download counter to $NEW_COUNT"
          git push
